# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: lendev4/pagels-kindergarten2
#backend:
#  name: test-repo

media_folder: /public/uploads
public_folder: /uploads

collections:
  - name: "homepage"
    label: "Startseite"
    files: 
      - label: "Startseite bearbeiten"
        name: "homepage"
        file: "src/content/homepage/homepage.md"
        fields:
        - { label: Überschrift, name: headline, widget: string }
        - { label: Zitat, name: quote, widget: text, required: false }
        - { label: Zitat Autor, name: quote_author, widget: string, required: false }
        - { label: Titelbild, name: cover_image, widget: image, required: false }

  - name: "homepage_sections"
    label: "Startseite Sektionen"
    folder: src/content/homepage_sections
    create: true
    fields:
      - { label: Titel, name: section_title, widget: string }
      - { label: Reihenfolge, name: order, widget: number, required: false, hint: "Je kleiner die Zahl, desto weiter vorne" }
      - { label: Farbe, name: color, widget: select, options: [{label: Rot, value: ""}, { label: Blau, value: blue }, { label: Grün, value: green }, { label: Lila, value: purple }], required: false }
      - { label: Bild links, name: image_on_left, widget: boolean, required: false }
      - { label: Bild, name: section_image, widget: image, required: false }
      - { label: Inhalt, name: body, widget: markdown }

  - name: "gallery"
    label: "Galerie"
    folder: src/content/gallery
    create: true
    fields:
      - { label: Titel, name: title, widget: string }
      - { label: Beschreibung, name: description, widget: text, required: false }
      - { label: Reihenfolge, name: order, widget: number, required: false, hint: "Je kleiner die Zahl, desto weiter vorne" }
      - { label: Farbe, name: color, widget: select, options: [{label: Rot, value: ""}, { label: Blau, value: blue }, { label: Grün, value: green }, { label: Lila, value: purple }], required: false }
      - { label: Bilder, name: images, widget: list, allow_add: true, required: false, field: { label: Bild, name: image, widget: image } }
        
  - name: "pages"
    label: "Seiten"
    folder: src/content/pages
    create: true
    fields:
      - { label: "In Navigationsleiste anzeigen", name: nav, widget: boolean, default: false, required: false }
      - { label: "Navigationslabel", name: nav_label, widget: string, required: false, hint: "Verwende Titel, falls leer" }
      - { label: "Reihenfolge in der Navigation", name: nav_order, widget: number, required: false, hint: "Je kleiner die Zahl, desto weiter vorne" }
      - { label: "Farbe", name: color, widget: select, options: [{label: Rot, value: ""}, { label: Blau, value: blue }, { label: Grün, value: green }, { label: Lila, value: purple }], required: false }
      - { label: Titel, name: title, widget: string }
      - { label: Inhalt, name: body, widget: markdown }

  - name: "legal"
    label: "Rechtliches"
    folder: src/content/legal
    create: true
    fields:
      - { label: Titel, name: title, widget: string }
      - { label: Inhalt, name: body, widget: markdown }